const profileTypes = {
  PROFILE_REQUESTED: 'PROFILE_REQUESTED',
  PROFILE_SUCCEED: 'PROFILE_SUCCEED',
  PROFILE_FAILURE: 'PROFILE_FAILURE',
  //
  UPDATE_PROFILE_REQUESTED: 'UPDATE_PROFILE_REQUESTED',
  UPDATE_PROFILE_SUCCEED: 'UPDATE_PROFILE_SUCCEED',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
  //
  CHECK_OPEN_TO: 'CHECK_OPEN_TO',
  CHECK_AVAILABILITY: 'CHECK_AVAILABILITY',
  CHECK_LOCATION: 'CHECK_LOCATION',
  CHECK_PREFERRED_TIME: 'CHECK_PREFERRED_TIME',
  SWITCH_TO_BE_CONTACTED: 'SWITCH_TO_BE_CONTACTED',
  PUT_TO_BE_CONTACTED: 'PUT_TO_BE_CONTACTED',
  CHECK_PREFERRED_MISSIONS: 'CHECK_PREFERRED_MISSIONS',
  CHECK_PREFERRED_INDUSTRIES: 'CHECK_PREFERRED_INDUSTRIES',
  CHECK_SPECIALITY: 'CHECK_SPECIALITY',
  CHECK_LEVEL: 'CHECK_LEVEL',
  REMOVE_SPECIALITY: 'REMOVE_SPECIALITY',
  ADD_SPECIALITY: 'ADD_SPECIALITY',
  RATE_SALARY: 'RATE_SALARY',
  ADD_LINK: 'ADD_LINK',
  //
  LOAD_LOCATIONS_TO_WORK: 'LOAD_LOCATIONS_TO_WORK',
  LOAD_CHECKED_INDUSTRIES: 'LOAD_CHECKED_INDUSTRIES',
  LOAD_CHECKED_MISSIONS: 'LOAD_CHECKED_MISSIONS',
  LOAD_CHECKED_SPECIALITIES: 'LOAD_CHECKED_SPECIALITIES',
  //
  GET_SELECTORS_DATA_REQUESTED: 'GET_SELECTORS_DATA_REQUESTED',
  GET_INDUSTRIES_SUCCEED: 'GET_INDUSTRIES_SUCCEED',
  GET_MISSIONS_SUCCEED: 'GET_MISSIONS_SUCCEED',
  GET_SPECIALITIES_SUCCEED: 'GET_SPECIALITIES_SUCCEED',
  // MODAL
  OPEN_GLOBAL_MODAL: 'OPEN_GLOBAL_MODAL',
  CLOSE_GLOBAL_MODAL: 'CLOSE_GLOBAL_MODAL',
  PUT_GLOBAL_MODAL_FN: 'PUT_GLOBAL_MODAL_FN',
};

export default profileTypes;
