const eventsTypes = {
  ADD_TO_MINE: 'ADD_TO_MINE',
  REMOVE_FROM_MINE: 'REMOVE_FROM_MINE',
  REMOVE_FROM_ALL: 'REMOVE_FROM_ALL',
  // GET ALL EVENTS
  ALL_EVENTS_REQUESTED: 'ALL_EVENTS_REQUESTED',
  ALL_EVENTS_SUCCEED: 'ALL_EVENTS_SUCCEED',
  ALL_EVENTS_SUCCEED_PAGINATION: 'ALL_EVENTS_SUCCEED_PAGINATION',
  ALL_EVENTS_FAILED: 'ALL_EVENTS_FAILED',
  // GET MINE EVENTS
  MINE_EVENTS_REQUESTED: 'MINE_EVENTS_REQUESTED',
  MINE_EVENTS_SUCCEED: 'MINE_EVENTS_SUCCEED',
  MINE_EVENTS_SUCCEED_PAGINATION: 'MINE_EVENTS_SUCCEED_PAGINATION',
  MINE_EVENTS_FAILED: 'MINE_EVENTS_FAILED',
  // ATTACH EVENT
  ATTACH_EVENT_REQUESTED: 'ATTACH_EVENT_REQUESTED',
  ATTACH_EVENT_SUCCEED: 'ATTACH_EVENT_SUCCEED',
  ATTACH_EVENT_FAILURE: 'ATTACH_EVENT_FAILURE',
  // DETACH EVENT
  DETACH_EVENT_REQUESTED: 'DETACH_EVENT_REQUESTED',
  DETACH_EVENT_SUCCEED: 'DETACH_EVENT_SUCCEED',
  DETACH_EVENT_FAILURE: 'DETACH_EVENT_FAILURE',
  // DROP DOWN EVENT
  DROP_DOWN_EVENT_REQUESTED: 'DROP_DOWN_EVENT_REQUESTED',
  DROP_DOWN_EVENT_SUCCEED: 'DROP_DOWN_EVENT_SUCCEED',
  DROP_DOWN_EVENT_FAILED: 'DROP_DOWN_EVENT_FAILED',
};

export default eventsTypes;
