const authTypes = {
  AUTH: 'AUTH',
  REGISTRATION_REQUESTED: 'REGISTRATION_REQUESTED',
  REGISTRATION_SUCCEED: 'REGISTRATION_SUCCEED',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  //
  CONFIRM_EMAIL_REQUESTED: 'CONFIRM_EMAIL_REQUESTED',
  CONFIRM_EMAIL_SUCCEED: 'CONFIRM_EMAIL_SUCCEED',
  CONFIRM_EMAIL_FAILED: 'CONFIRM_EMAIL_FAILED',
  //
  RE_SEND_CONFIRMATION_REQUESTED: 'RE_SEND_CONFIRMATION_REQUESTED',
  RE_SEND_CONFIRMATION_SUCCEED: 'RE_SEND_CONFIRMATION_SUCCEED',
  RE_SEND_CONFIRMATION_FAILED: 'RE_SEND_CONFIRMATION_FAILED',
  // LOGIN
  LOGIN_REQUESTED: 'LOGIN_REQUESTED',
  LOGIN_SUCCEED: 'LOGIN_SUCCEED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  AGREE_TERMS_CONDITIONS: 'AGREE_TERMS_CONDITIONS',
  // RESET PASSWORD
  RESET_PASSWORD_REQUESTED: 'RESET_PASSWORD_REQUESTED',
  RESET_PASSWORD_SUCCEED: 'RESET_PASSWORD_SUCCEED',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
  //
  VERIFY_RESET_PASSWORD_REQUESTED: 'VERIFY_RESET_PASSWORD_REQUESTED',
  VERIFY_RESET_PASSWORD_SUCCEED: 'VERIFY_RESET_PASSWORD_SUCCEED',
  VERIFY_RESET_PASSWORD_FAILED: 'VERIFY_RESET_PASSWORD_FAILED',
  //
  RESET_PASSWORD_COMPLETE_REQUESTED: 'RESET_PASSWORD_COMPLETE_REQUESTED',
  RESET_PASSWORD_COMPLETE_SUCCEED: 'RESET_PASSWORD_COMPLETE_SUCCEED',
  RESET_PASSWORD_COMPLETE_FAILED: 'RESET_PASSWORD_COMPLETE_FAILED',
  //
  USER_STATUS_REQUESTED: 'USER_STATUS_REQUESTED',
  USER_STATUS_SUCCEED: 'USER_STATUS_SUCCEED',
  USER_STATUS_FAILED: 'USER_STATUS_FAILED',
  //
  PUT_PROFILE_REQUESTED: 'PUT_PROFILE_REQUESTED',
  PUT_PROFILE_SUCCEED: 'PUT_PROFILE_SUCCEED',
  PUT_PROFILE_FAILED: 'PUT_PROFILE_FAILED',
  //
  CLEAR_FILLED_PROFILE: 'CLEAR_FILLED_PROFILE',
};

export default authTypes;
