const opportunitiesTypes = {
  // GET ALL
  ALL_OPPORTUNITIES_REQUESTED: 'ALL_OPPORTUNITIES_REQUESTED',
  ALL_OPPORTUNITIES_SUCCEED: 'ALL_OPPORTUNITIES_SUCCEED',
  ALL_OPPORTUNITIES_SUCCEED_PAGINATION: 'ALL_OPPORTUNITIES_SUCCEED_PAGINATION',
  ALL_OPPORTUNITIES_FAILURE: 'ALL_OPPORTUNITIES_FAILURE',
  // GET MINE
  MINE_OPPORTUNITIES_REQUESTED: 'MINE_OPPORTUNITIES_REQUESTED',
  MINE_OPPORTUNITIES_SUCCEED: 'MINE_OPPORTUNITIES_SUCCEED',
  MINE_OPPORTUNITIES_SUCCEED_PAGINATION: 'MINE_OPPORTUNITIES_SUCCEED_PAGINATION',
  MINE_OPPORTUNITIES_FAILURE: 'MINE_OPPORTUNITIES_FAILURE',
  // ATTACH
  ATTACH_OPPORTUNITY_REQUESTED: 'ATTACH_OPPORTUNITY_REQUESTED',
  ATTACH_OPPORTUNITY_SUCCEED: 'ATTACH_OPPORTUNITY_SUCCEED',
  ATTACH_OPPORTUNITY_FAILURE: 'ATTACH_OPPORTUNITY_FAILURE',
  // DETACH
  DETACH_OPPORTUNITY_REQUESTED: 'DETACH_OPPORTUNITY_REQUESTED',
  DETACH_OPPORTUNITY_SUCCEED: 'DETACH_OPPORTUNITY_SUCCEED',
  DETACH_OPPORTUNITY_FAILURE: 'DETACH_OPPORTUNITY_FAILURE',
  // GET ALL USERS ALERTS
  GET_ALL_USERS_ALERTS_REQUESTED: 'GET_ALL_USERS_ALERTS_REQUESTED',
  GET_ALL_USERS_ALERTS_SUCCEED: 'GET_ALL_USERS_ALERTS_SUCCEED',
  GET_ALL_USERS_ALERTS_SUCCEED_PAGINATION: 'GET_ALL_USERS_ALERTS_SUCCEED_PAGINATION',
  GET_ALL_USERS_ALERTS_FAILURE: 'GET_ALL_USERS_ALERTS_FAILURE',
  // SELECT OPPORTUNITY
  SELECT_OPPORTUNITY: 'SELECT_OPPORTUNITY',
  // DROP DOWN OPPORTUNITY FROM ALL
  DROP_DOWN_OPPORTUNITY_REQUESTED: 'DROP_DOWN_OPPORTUNITY_FROM_ALL_REQUESTED',
  DROP_DOWN_OPPORTUNITY_SUCCEED: 'DROP_DOWN_OPPORTUNITY_FROM_ALL_SUCCEED',
  DROP_DOWN_OPPORTUNITY_FAILED: 'DROP_DOWN_OPPORTUNITY_FROM_ALL_FAILED',
  // CREATE OPPORTUNITY
  CREATE_ALERT_OPPORTUNITY_REQUESTED: 'CREATE_ALERT_OPPORTUNITY_REQUESTED',
  CREATE_ALERT_OPPORTUNITY_SUCCEED: 'CREATE_ALERT_OPPORTUNITY_SUCCEED',
  CREATE_ALERT_OPPORTUNITY_FAILURE: 'CREATE_ALERT_OPPORTUNITY_FAILURE',
  // GET ALERT RESPOND BY ID
  GET_ALERT_RESPOND_BY_ID_REQUESTED: 'GET_ALERT_RESPOND_BY_ID_REQUESTED',
  GET_ALERT_RESPOND_BY_ID_SUCCEED: 'GET_ALERT_RESPOND_BY_ID_SUCCEED',
  GET_ALERT_RESPOND_BY_ID_FAILURE: 'GET_ALERT_RESPOND_BY_ID_FAILURE',
};

export default opportunitiesTypes;
