const homeTypes = {
  OWN_REQUESTS_REQUESTED: 'OWN_REQUESTS_REQUESTED',
  OWN_REQUESTS_SUCCEED: 'OWN_REQUESTS_SUCCEED',
  OWN_REQUESTS_SUCCEED_PAGINATION: 'OWN_REQUESTS_SUCCEED_PAGINATION',
  OWN_REQUESTS_FAILED: 'OWN_REQUESTS_FAILED',
  //
  CREATE_FEATURE_REQUEST_REQUESTED: 'CREATE_FEATURE_REQUEST_REQUESTED',
  CREATE_FEATURE_REQUEST_SUCCEED: 'CREATE_FEATURE_REQUEST_SUCCEED',
  CREATE_FEATURE_REQUEST_FAILURE: 'CREATE_FEATURE_REQUEST_FAILURE',
  //
  GET_REQUEST_RESPOND_BY_ID: 'GET_REQUEST_RESPOND_BY_ID',
};

export default homeTypes;
